// Beat-locked timing.
//
// The backing track is generated by us, so its tempo is an input rather than a
// guess. Deriving every cut and every text arrival from the beat grid is the
// single biggest thing separating authored motion from generic animation —
// see docs/VIDEO_CRAFT.md. Nothing in the template should use a raw frame
// count.

import { FPS } from "./schema";

export interface Grid {
  bpm: number;
  /** Frames per beat. */
  beat: number;
  /** Frames per bar (4/4). */
  bar: number;
  /** Frame number of beat n. */
  atBeat: (n: number) => number;
  /** Frame number of bar n. */
  atBar: (n: number) => number;
  /** Round a frame count UP to the next whole bar. */
  quantizeUp: (frames: number) => number;
}

export function makeGrid(bpm: number): Grid {
  const beat = (60 / bpm) * FPS;
  const bar = beat * 4;
  return {
    bpm,
    beat,
    bar,
    atBeat: (n) => Math.round(n * beat),
    atBar: (n) => Math.round(n * bar),
    quantizeUp: (frames) => Math.max(Math.round(bar), Math.ceil(frames / bar) * Math.round(bar)),
  };
}

/**
 * Stagger delays for a list, one beat apart by default.
 *
 * Elements arriving together give the eye nowhere to land; each item gets its
 * own beat and settles before the next moves.
 */
export function staggerBeats(grid: Grid, count: number, startBeat = 1, step = 1): number[] {
  return Array.from({ length: count }, (_, i) => grid.atBeat(startBeat + i * step));
}
